// Generated by CoffeeScript 1.6.2
(function() {
  var app;

  app = angular.module('client', ['ui', 'ui.bootstrap', 'ether']);

  app.controller('MainCtrl', function($scope, collection, rpc) {
    $scope.collection = collection;
    $scope.data = collection('test').data;
    $scope.stats = collection('stats').data;
    $scope.clients = collection('clients').data;
    $scope.myself = function() {
      return collection('users:self').data;
    };
    $scope.myroom = function() {
      return collection('myroom').data;
    };
    window.rpc = rpc;
    $scope.rpc = rpc;
    return setInterval((function() {
      var _ref, _ref1, _ref2;

      if (((_ref = $scope.myroom()) != null ? _ref.owner : void 0) == null) {
        return (_ref1 = rpc.room) != null ? (_ref2 = _ref1["in"]) != null ? _ref2.claimOwner() : void 0 : void 0;
      }
    }), 1000);
  });

}).call(this);
