// Generated by CoffeeScript 1.6.2
(function() {
  var app;

  app = angular.module('client', ['ui', 'ui.bootstrap', 'ether']);

  app.controller('MainCtrl', function($scope, collection, rpc) {
    $scope.collection = collection;
    $scope.data = collection('test').data;
    $scope.stats = collection('stats').data;
    $scope.clients = collection('clients').data;
    $scope.myself = function() {
      var _ref;

      return (_ref = collection('users:self').data) != null ? _ref[0] : void 0;
    };
    $scope.myroom = function() {
      var _ref;

      return (_ref = collection('myroom').data) != null ? _ref[0] : void 0;
    };
    return $scope.rpc = rpc;
  });

}).call(this);
